### ISSUE TITLE
每日JD的“超级秒杀”用什么模式？

### ISSUE THREAD

**Issue by hongyubaobao** [whyour/jd-assistant#1]
请教大佬：原作者tychxn设置了几种模式：3.1.1直接提交订单、3.1.2定时提交订单、3.1.3有货提交订单，还有个停止更新的3.2.1定时执行抢购请求。请教一下每日JD的“超级秒杀”用什么模式的代码？

**Comment by whyour** [comment]
3.2.1

**Comment by hongyubaobao** [comment]
> 3.2.1

谢谢老大的回复。3.2.1代码已被原作者隐藏了，您这里有备份吗？（我手里也有一份，试过，无法成功。不确定是不是3.2.1的代码，具体见下：）
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from jd_assistant import Assistant
from util import parse_time, parse_sku_id_to_list
import pdb
import threading
import time

from log import logger

'''
抢购线程
'''
class BuyProcess (threading.Thread):
    def __init__(self, threadID, skuid, buy_time, asst, num):
        threading.Thread.__init__(self)
        self.threadID = threadID
        self.skuid = skuid
        self.buy_time = buy_time
        self.asst = asst
        self.num = num
    def run(self):
        self.asst.exec_seckill_by_time(self.skuid, self.buy_time, num=self.num)

'''
预定线程
'''
class ReserveProcess (threading.Thread):
    def __init__(self, threadID, skuid, reserve_time, buy_time, asst):
        threading.Thread.__init__(self)
        self.threadID = threadID
        self.skuid = skuid
        self.reserve_time = reserve_time
        self.buy_time = buy_time
        self.asst = asst
    def run(self):
        self.asst.make_reserve_on_time(self.skuid, self.reserve_time)


if __name__ == '__main__':

    sku_ids = '65708238590,100011521400,65624145328,100006394713,100011551632'  # 商品id
    sku_nums = '1,1,1,1,1'
    all_reserve_time = '10:59:30.000,20:59:30.000,10:59:30.000,14:59:30.000,14:59:30.000'
    all_buy_time = '17:00:00.050,10:00:00.050,15:00:00.050,20:00:00.050,20:00:00.050'
    area = '1_2812_51129'  # 区域id
    max_reserve_threads_num = 6


    asst = Assistant()  # 初始化
    asst.login_by_QRcode()  # 扫码登陆

    # 转list和dict
    sku_ids_list = parse_sku_id_to_list(sku_ids)
    reserve_time_list = parse_time(all_reserve_time)
    buy_time_list = parse_time(all_buy_time)

    i=0

    for (sku_id, reserve_time, buy_time, sku_num) in zip(sku_ids_list, reserve_time_list, buy_time_list, sku_nums):
        local_time = time.strftime("%Y-%m-%d %H:%M:%S",time.localtime(time.time()))
        if reserve_time[:len(local_time)]>local_time:
            cur_reserve_process = ReserveProcess(i, sku_id, reserve_time, buy_time, asst)
            cur_reserve_process.start()
            logger.info('%s 预约进程开启', sku_id)
            time.sleep(2)
        else:
            logger.info('%s 预约时间已过', sku_id)
            time.sleep(2)
        if buy_time[:len(local_time)]>local_time:
            cur_buy_process = BuyProcess(i+1, sku_id, buy_time, asst, sku_num)
            cur_buy_process.start()
            logger.info('%s 购买进程开启', sku_id)
            time.sleep(2)
        else:
            logger.info('%s 购买时间已过', sku_id)
            time.sleep(2)
        i += 2

**Comment by whyour** [comment]
> > 3.2.1
> 
> 谢谢老大的回复。3.2.1代码已被原作者隐藏了，您这里有备份吗？（我手里也有一份，试过，无法成功。不确定是不是3.2.1的代码，具体见下：）
> #!/usr/bin/env python
> 
> # -_- coding:utf-8 -_-
> from jd_assistant import Assistant
> from util import parse_time, parse_sku_id_to_list
> import pdb
> import threading
> import time
> 
> from log import logger
> 
> '''
> 抢购线程
> '''
> class BuyProcess (threading.Thread):
> def **init**(self, threadID, skuid, buy_time, asst, num):
> threading.Thread.**init**(self)
> self.threadID = threadID
> self.skuid = skuid
> self.buy_time = buy_time
> self.asst = asst
> self.num = num
> def run(self):
> self.asst.exec_seckill_by_time(self.skuid, self.buy_time, num=self.num)
> 
> '''
> 预定线程
> '''
> class ReserveProcess (threading.Thread):
> def **init**(self, threadID, skuid, reserve_time, buy_time, asst):
> threading.Thread.**init**(self)
> self.threadID = threadID
> self.skuid = skuid
> self.reserve_time = reserve_time
> self.buy_time = buy_time
> self.asst = asst
> def run(self):
> self.asst.make_reserve_on_time(self.skuid, self.reserve_time)
> 
> if **name** == '**main**':
> 
> ```
> sku_ids = '65708238590,100011521400,65624145328,100006394713,100011551632'  # 商品id
> sku_nums = '1,1,1,1,1'
> all_reserve_time = '10:59:30.000,20:59:30.000,10:59:30.000,14:59:30.000,14:59:30.000'
> all_buy_time = '17:00:00.050,10:00:00.050,15:00:00.050,20:00:00.050,20:00:00.050'
> area = '1_2812_51129'  # 区域id
> max_reserve_threads_num = 6
> 
> 
> asst = Assistant()  # 初始化
> asst.login_by_QRcode()  # 扫码登陆
> 
> # 转list和dict
> sku_ids_list = parse_sku_id_to_list(sku_ids)
> reserve_time_list = parse_time(all_reserve_time)
> buy_time_list = parse_time(all_buy_time)
> 
> i=0
> 
> for (sku_id, reserve_time, buy_time, sku_num) in zip(sku_ids_list, reserve_time_list, buy_time_list, sku_nums):
>     local_time = time.strftime("%Y-%m-%d %H:%M:%S",time.localtime(time.time()))
>     if reserve_time[:len(local_time)]>local_time:
>         cur_reserve_process = ReserveProcess(i, sku_id, reserve_time, buy_time, asst)
>         cur_reserve_process.start()
>         logger.info('%s 预约进程开启', sku_id)
>         time.sleep(2)
>     else:
>         logger.info('%s 预约时间已过', sku_id)
>         time.sleep(2)
>     if buy_time[:len(local_time)]>local_time:
>         cur_buy_process = BuyProcess(i+1, sku_id, buy_time, asst, sku_num)
>         cur_buy_process.start()
>         logger.info('%s 购买进程开启', sku_id)
>         time.sleep(2)
>     else:
>         logger.info('%s 购买时间已过', sku_id)
>         time.sleep(2)
>     i += 2
> ```

不是这个方法吗  `exec_seckill_by_time `

**Comment by hongyubaobao** [comment]
> > > 3.2.1
> > 
> > 
> > 谢谢老大的回复。3.2.1代码已被原作者隐藏了，您这里有备份吗？（我手里也有一份，试过，无法成功。不确定是不是3.2.1的代码，具体见下：）

> > ```
> 
> 不是这个方法吗 `exec_seckill_by_time `

不行的，反馈是：
2021-01-13 12:00:00,260 INFO: 抢购链接获取失败，100017684578不是抢购商品或抢购页面暂未刷新，稍后重试

**Comment by whyour** [comment]
> > > > 3.2.1
> > > 
> > > 
> > > 谢谢老大的回复。3.2.1代码已被原作者隐藏了，您这里有备份吗？（我手里也有一份，试过，无法成功。不确定是不是3.2.1的代码，具体见下：）
> 
> > > 
> > 
> > 
> > 不是这个方法吗 `exec_seckill_by_time `
> 
> 不行的，反馈是：
> 2021-01-13 12:00:00,260 INFO: 抢购链接获取失败，100017684578不是抢购商品或抢购页面暂未刷新，稍后重试
这是不在抢购时间，抢购只有半小时
